Repository AnthonyHeinrichs/Dish-List-App, pull requests merged in 2022-03, with the labels that each got.

#5 seeded restaurants
  .gitignore
  app/controllers/restaurants_controller.rb
  app/views/restaurants/index.html.erb
  config/routes.rb
  db/seeds.rb
Labels: help wanted

#12 Style index
  app/assets/images/ramen_200.png
  app/assets/stylesheets/components/_banner.scss
  app/assets/stylesheets/components/_index.scss
  app/assets/stylesheets/config/_colors.scss
  app/assets/stylesheets/config/_fonts.scss
  app/javascript/controllers/change_photos_controller.js
  app/views/layouts/application.html.erb
  app/views/restaurants/index.html.erb
  app/views/shared/_banner.html.erb
  app/views/shared/_navbar.html.erb
Labels: bug, enhancement

#18 Banner fixup
  app/assets/stylesheets/components/_banner.scss
  app/assets/stylesheets/components/_cards.scss
  app/javascript/controllers/search_dishes_controller.js
  app/views/dishes/index.html.erb
  app/views/restaurants/index.html.erb
  app/views/shared/_banner.html.erb
Labels: bug, enhancement

#21 Dish popup
  Gemfile.lock
  app/assets/stylesheets/components/_modal.scss
  app/assets/stylesheets/config/_colors.scss
  app/views/dishes/_dish_modal.html.erb
Labels: bug, enhancement

#30 Tag restaurants
  app/assets/images/bretzel_400.png
  app/assets/images/burger_400.png
  app/assets/images/pizza_400.png
  app/assets/stylesheets/components/_banner.scss
  app/controllers/dishes_controller.rb
  app/javascript/controllers/search_dishes_controller.js
  app/models/dish.rb
  app/models/restaurant.rb
  app/views/dishes/index.html.erb
  db/seeds.rb
Labels: bug, enhancement

#33 added joint table seeds
  app/models/dish.rb
  app/models/restaurant.rb
  db/seeds.rb
Labels: bug

#40 Seed again
   
  README.md
  app/assets/images/icon_heart.png
  app/assets/images/icon_home.png
  app/assets/images/icon_star.png
  app/assets/images/icon_telephone.png
  app/assets/images/icon_upload.png
  app/assets/images/map_cocolo_460.png
  app/assets/images/tony_400.jpg
  app/assets/stylesheets/components/_cards.scss
  app/assets/stylesheets/components/_footer.scss
  app/assets/stylesheets/components/_index.scss
  app/assets/stylesheets/components/_modal.scss
  app/assets/stylesheets/components/_modalrestaurant.scss
  app/controllers/dishes_controller.rb
  app/controllers/restaurants_controller.rb
  app/models/restaurant.rb
  app/views/dishes/_dish_infos.html.erb
  app/views/dishes/_dish_modal.html.erb
  app/views/dishes/_list.html.erb
  app/views/dishes/index.html.erb
  app/views/layouts/application.html.erb
  app/views/restaurants/_restaurant_card.html.erb
  app/views/restaurants/_restaurant_modal.html.erb
  app/views/restaurants/index.html.erb
  app/views/shared/_footer.html.erb
  db/seeds.rb
  idd
Labels: bug, enhancement

#53 Frontend touchup
  app/assets/images/icon_dimond.png
  app/assets/images/icon_dimond_negative.png
  app/assets/stylesheets/components/_modal.scss
  app/assets/stylesheets/components/_modalrestaurant.scss
  app/assets/stylesheets/config/_bootstrap_variables.scss
  app/controllers/restaurants_controller.rb
  app/views/layouts/application.html.erb
  app/views/restaurants/_restaurant_modal.html.erb
  app/views/restaurants/index.html.erb
Labels: bug, enhancement

#55 Front night
  app/assets/images/icon_chili_1.png
  app/assets/images/icon_chili_2.png
  app/assets/images/icon_chili_3.png
  app/assets/images/icon_chili_4.png
  app/assets/images/icon_chili_5.png
  app/assets/stylesheets/components/_modalrestaurant.scss
  app/controllers/dishes_controller.rb
  app/views/dishes/_dish_infos.html.erb
  app/views/restaurants/_restaurant_card.html.erb
  app/views/restaurants/_restaurant_modal.html.erb
  app/views/restaurants/_review_form.html.erb
  app/views/restaurants/index.html.erb
  app/views/shared/_footer.html.erb
  db/migrate/20220308190556_add_details_to_dish.rb
  db/migrate/20220308194918_add_description_to_restaurant.rb
  db/schema.rb
  db/seeds.rb
Labels: bug, enhancement

#69 Bugfix
  app/views/layouts/application.html.erb
  db/schema.rb
  db/seeds.rb
Labels: bug
